name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

    - run: node --version
    - run: npm --version
    - run: npm install
    - run: yarn install
    - run: yarn start
    - run: node app.js
    - run: npm run build --if-present
    - run: npm test


      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user/react
          remote_host: 13.239.134.233
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"